### ISSUE TITLE
Put source code of adapers at first level folder

### ISSUE THREAD

**Issue by maidmaid** [php-cache/cache#1]
Currently, there are [one autoload for each adapter](https://github.com/php-cache/cache/blob/master/composer.json#L30-L46). I watched how Symfony did made them subtree splits and I note that source code is at first level folder, without src folder (for example, [console component](https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Console) in symfony project and [subtree split console](https://github.com/symfony/console)). By this way, autoload section in composer.json is [very simple](https://github.com/symfony/symfony/blob/master/composer.json#L101).

**Comment by Nyholm** [comment]
:+1:
